default_profile = "full-auto-mode"
approval_policy = "never"
file_opener = "vscode"
hide_agent_reasoning = true
model = "gpt-5"
model_reasoning_effort = "high"
network_access = true
notify = ["codex-notify-sound"]
sandbox_mode = "danger-full-access"

[history]
  persistence = "save-all"

[mcp_servers]

  [mcp_servers.context7]
    args = ["-y", "@upstash/context7-mcp@latest"]
    command = "npx"
    startup_timeout_sec = 20
    tool_timeout_sec = 60

  [mcp_servers.github]
    args = []
    command = "/home/user/.local/bin/github-mcp-stdio-native"
    startup_timeout_sec = 60
    tool_timeout_sec = 60
    transport = "stdio"

  [mcp_servers.supabase]
    args = []
    command = "/home/user/.local/bin/supabase-mcp-stdio"
    startup_timeout_sec = 20
    tool_timeout_sec = 60
    transport = "stdio"

  [mcp_servers.chrome-devtools]
    args = ["-y", "chrome-devtools-mcp@latest"]
    command = "npx"
    startup_timeout_sec = 20
    tool_timeout_sec = 60
    transport = "stdio"

  [mcp_servers.git]
    args = ["mcp-server-git"]
    command = "uvx"
    startup_timeout_sec = 60
    tool_timeout_sec = 60
    transport = "stdio"

  [mcp_servers.fetch]
    args = ["mcp-server-fetch"]
    command = "uvx"
    startup_timeout_sec = 60
    tool_timeout_sec = 60
    transport = "stdio"

  [mcp_servers.aws-api]
    args = ["awslabs.aws-api-mcp-server@latest"]
    command = "uvx"
    startup_timeout_sec = 60
    tool_timeout_sec = 120
    transport = "stdio"

[sandbox_workspace_write]
  exclude_slash_tmp = false
  exclude_tmpdir_env_var = false
  network_access = true
  writable_roots = ["/home/user/Development"]

[shell_environment_policy]
  exclude = []
  ignore_default_excludes = false
  include_only = []
  inherit = "all"

[profiles.full-auto-mode]
full-auto = true
